name       : ruby-neovim
version    : 0.8.0
release    : 9
source     :
    - https://rubygems.org/downloads/neovim-0.8.0.gem : d30f99d2ede6298c91297ced319020bbad8b9b545ed4d29f2cd6df335dcb4c1f
license    : MIT
component  : programming.ruby
extract    : no
summary    : RubyGem - neovim
description: |
    Ruby client for Neovim.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - neovim
    - ruby-msgpack
    - ruby-multi_json
install    : |
    %gem_install
