name       : ruby-neovim
version    : 0.3.3
release    : 2
source     :
    - https://rubygems.org/downloads/neovim-0.3.3.gem : db87d1101598c76c554a236cb8a3edc0f39d61e044e99a1e7ec3571b24ed18c3
license    : MIT
component  : programing
summary    : Ruby client for Neovim
description: |
    Ruby client for Neovim
builddeps  :
    - pkgconfig(ruby-2.2)
rundeps    :
    - ruby-msgpack
install    : |
    export geminstalldir=$(ruby -e'puts Gem.default_dir')
    export GEM_HOME=$geminstalldir
    export GEM_PATH=$geminstalldir
    gem install \
        --ignore-dependencies \
        --no-user-install \
        -i "$installdir/$geminstalldir" \
        -n "$installdir/usr/bin" \
        $sources/neovim-$version.gem
