name       : ruby-neovim
version    : 0.7.0
release    : 5
source     :
    - https://rubygems.org/downloads/neovim-0.7.0.gem : 042fb77d7f88635cf357f02fb6e7ade6e639917b58bafd39433506f27f3b882c
license    : MIT
component  : programming.ruby
extract    : no
summary    : RubyGem - neovim
description: |
    Ruby client for Neovim.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - neovim
    - ruby-msgpack
    - ruby-multi_json
install    : |
    %gem_install
