name       : ruby-neovim
version    : 0.4.0
release    : 3
source     :
    - https://rubygems.org/downloads/neovim-0.4.0.gem : 22d92f343c5b8a43bc8fe208f5e2562cf0653d1516925e803951e5387f507cbf
license    : MIT
component  : programing
summary    : Ruby client for Neovim
description: |
    Ruby client for Neovim
builddeps  :
    - pkgconfig(ruby-2.2)
rundeps    :
    - ruby-msgpack
install    : |
    export geminstalldir=$(ruby -e'puts Gem.default_dir')
    export GEM_HOME=$geminstalldir
    export GEM_PATH=$geminstalldir
    gem install \
        --ignore-dependencies \
        --no-user-install \
        -i "$installdir/$geminstalldir" \
        -n "$installdir/usr/bin" \
        $sources/neovim-$version.gem
